"""add_description_to_users

Revision ID: dd3a6bff2653
Revises: ec2251aade6a
Create Date: 2026-05-31 14:18:56.157750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd3a6bff2653"
down_revision: Union[str, None] = "ec2251aade6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("description", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "description")
    # ### end Alembic commands ###
