[package]
name = "sequence_of_steps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sequence_of_steps"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
