
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUAL FROM IDENTIFIER NUMBER SELECT STRING WHEREquery : SELECT IDENTIFIER FROM IDENTIFIER WHERE conditioncondition : IDENTIFIER EQUAL NUMBER\n                | IDENTIFIER EQUAL STRING'
    
_lr_action_items = {'SELECT':([0,],[2,]),'$end':([1,8,10,11,],[0,-1,-2,-3,]),'IDENTIFIER':([2,4,6,],[3,5,7,]),'FROM':([3,],[4,]),'WHERE':([5,],[6,]),'EQUAL':([7,],[9,]),'NUMBER':([9,],[10,]),'STRING':([9,],[11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'condition':([6,],[8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> SELECT IDENTIFIER FROM IDENTIFIER WHERE condition','query',6,'p_query','test.py',52),
  ('condition -> IDENTIFIER EQUAL NUMBER','condition',3,'p_condition','test.py',61),
  ('condition -> IDENTIFIER EQUAL STRING','condition',3,'p_condition','test.py',62),
]
